import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { CalendarCheckIcon, CheckCircleIcon, ClockCountdownIcon, DownloadSimpleIcon, WarningIcon } from "@phosphor-icons/react";
import { mockApi } from "@nicepatrol/mock-api";
import { Button, LayerCard, MetricCard, PageHeading, StatusBadge } from "@nicepatrol/ui";
import { ActionNotice } from "../../components/feedback/ActionNotice";
import { ShiftFormDialog } from "../../components/forms/ShiftFormDialog";
import type { ShiftFormValues } from "../../components/forms/formSchemas";

export function AttendancePage() {
  const [shiftDialogOpen, setShiftDialogOpen] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const { data: personnel=[] } = useQuery({queryKey:["personnel"],queryFn:mockApi.getPersonnel});
  const handleShift = (values: ShiftFormValues) => setNotice(`${values.name} assigned to ${values.officer} on ${values.date}, ${values.startsAt}–${values.endsAt}.`);
  return <div className="grid gap-6"><PageHeading eyebrow="Digital attendance" title="Attendance and shifts" description="Monitor presence, punctuality, and field verification for all security personnel." action={<Button variant="primary" icon={CalendarCheckIcon} onClick={() => setShiftDialogOpen(true)}>Manage shifts</Button>}/><ActionNotice message={notice} onDismiss={() => setNotice(null)} /><div className="grid gap-3 sm:grid-cols-3"><MetricCard label="Present today" value="34" detail="82.9% of assigned personnel" icon={CheckCircleIcon} tone="success"/><MetricCard label="Late arrivals" value="3" detail="Average delay: 12 minutes" icon={ClockCountdownIcon} tone="warning"/><MetricCard label="Not checked in" value="4" detail="2 excused, 2 unconfirmed" icon={WarningIcon} tone="critical"/></div><LayerCard className="overflow-hidden shadow-sm ring-1 ring-[var(--np-line)]"><div className="flex items-center justify-between border-b border-[var(--np-line)] px-4 py-3"><p className="font-medium">Today’s attendance</p><Button variant="secondary" icon={DownloadSimpleIcon}>Export</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-50 text-xs text-[var(--np-muted)]"><tr>{["Personnel","Shift","Area","Check-in","Verification","Status"].map((header)=><th key={header} className="px-4 py-3 font-medium">{header}</th>)}</tr></thead><tbody>{personnel.map((person)=><tr key={person.id} className="border-t border-[var(--np-line)]"><td className="px-4 py-3"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-slate-100 text-xs font-medium">{person.initials}</span><div><p className="font-medium">{person.name}</p><p className="font-mono text-[11px] text-[var(--np-muted)]">{person.id}</p></div></div></td><td className="px-4 py-3">{person.shift}</td><td className="px-4 py-3">{person.area}</td><td className="px-4 py-3 font-mono text-[12px]">{person.time}</td><td className="px-4 py-3"><span className="flex items-center gap-1.5 text-xs text-emerald-700"><CheckCircleIcon size={15} weight="fill"/>GPS + selfie</span></td><td className="px-4 py-3"><StatusBadge tone={person.status === "Late" ? "critical" : person.status === "Off duty" ? "neutral" : "success"}>{person.status}</StatusBadge></td></tr>)}</tbody></table></div></LayerCard><ShiftFormDialog open={shiftDialogOpen} onOpenChange={setShiftDialogOpen} onSubmit={handleShift} /></div>;
}
