import { useState } from "react";
import { NavLink } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { ArrowRightIcon, CheckCircleIcon, ClockCountdownIcon, IdentificationCardIcon, PlusIcon, SirenIcon, TrendUpIcon, UsersThreeIcon, WarningIcon } from "@phosphor-icons/react";
import { mockApi } from "@nicepatrol/mock-api";
import { Button, LayerCard, MetricCard, PageHeading, StatusBadge } from "@nicepatrol/ui";
import { PatrolCoverageChart } from "../../components/charts/PatrolCoverageChart";
import { SectionHeading } from "../../components/SectionHeading";
import { ActionNotice } from "../../components/feedback/ActionNotice";
import { PatrolFormDialog } from "../../components/forms/PatrolFormDialog";
import type { PatrolFormValues } from "../../components/forms/formSchemas";

export function OverviewPage() {
  const [patrolDialogOpen, setPatrolDialogOpen] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const { data: patrols = [] } = useQuery({ queryKey: ["patrols"], queryFn: mockApi.getPatrols });
  const { data: personnel = [] } = useQuery({ queryKey: ["personnel"], queryFn: mockApi.getPersonnel });
  const handleCreatePatrol = (values: PatrolFormValues) => setNotice(`${values.route} created for ${values.officer} on ${values.date} at ${values.startTime}.`);
  return <div className="grid gap-6">
    <PageHeading eyebrow="Wednesday, 12 August 2026" title="Good morning, Agus" description="Here is the current security operation across all work areas." action={<Button variant="primary" icon={PlusIcon} onClick={() => setPatrolDialogOpen(true)}>Create patrol</Button>}/>
    <ActionNotice message={notice} onDismiss={() => setNotice(null)} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Personnel on duty" value="34" detail="of 41 assigned today" icon={UsersThreeIcon}/><MetricCard label="Patrol completion" value="92%" detail="+4.2% from last week" icon={TrendUpIcon} tone="success"/><MetricCard label="Active visitors" value="12" detail="3 expected to check out" icon={IdentificationCardIcon} tone="warning"/><MetricCard label="Open incidents" value="2" detail="1 requires attention" icon={SirenIcon} tone="critical"/></div>
    <div className="grid gap-5 xl:grid-cols-[1.55fr_1fr]"><div><SectionHeading title="Patrol coverage" action={<button className="text-xs font-medium text-[var(--np-brand)]">View report</button>}/><LayerCard className="px-5 py-4 shadow-sm ring-1 ring-[var(--np-line)]"><div className="mb-2 flex flex-wrap items-center justify-between gap-3"><div><p className="text-[22px] font-semibold">92.4%</p><p className="text-xs text-[var(--np-muted)]">Average completion · last 7 days</p></div><div className="flex items-center gap-4 text-xs text-[var(--np-muted)]"><span className="flex items-center gap-1.5"><i className="size-2 rounded-full bg-[var(--np-brand)]"/>Completed</span><span className="flex items-center gap-1.5"><i className="size-2 rounded-full bg-sky-200"/>Target</span></div></div><PatrolCoverageChart/></LayerCard></div>
      <div><SectionHeading title="Requires attention"/><LayerCard className="overflow-hidden shadow-sm ring-1 ring-[var(--np-line)]"><div className="flex items-start gap-3 bg-rose-50 px-4 py-3.5"><span className="h-lh flex items-center text-rose-600"><WarningIcon size={19} weight="fill"/></span><div className="grid flex-1 gap-1"><div className="flex items-center justify-between"><p className="font-medium">Emergency exit obstructed</p><StatusBadge tone="critical">High</StatusBadge></div><p className="text-xs text-[var(--np-muted)]">Warehouse B · reported by Rizky Pratama</p><p className="text-xs text-[var(--np-muted)]">8 minutes ago</p></div></div><div className="flex items-start gap-3 border-t border-[var(--np-line)] px-4 py-3.5"><span className="h-lh flex items-center text-amber-600"><ClockCountdownIcon size={19} weight="fill"/></span><div className="grid flex-1 gap-1"><p className="font-medium">Patrol Alpha-02 is delayed</p><p className="text-xs text-[var(--np-muted)]">Checkpoint CP-07 overdue by 12 minutes</p><p className="text-xs text-[var(--np-muted)]">3 minutes ago</p></div></div><button className="flex w-full items-center justify-center gap-2 border-t border-[var(--np-line)] px-4 py-3 text-xs font-medium text-[var(--np-brand)] hover:bg-slate-50">View all alerts <ArrowRightIcon size={14}/></button></LayerCard></div></div>
    <div className="grid gap-5 xl:grid-cols-[1.55fr_1fr]"><div><SectionHeading title="Active patrols" action={<NavLink to="/patrols" className="text-xs font-medium text-[var(--np-brand)]">View all</NavLink>}/><LayerCard className="overflow-hidden shadow-sm ring-1 ring-[var(--np-line)]"><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead className="bg-slate-50 text-xs text-[var(--np-muted)]"><tr><th className="px-4 py-3 font-medium">Patrol</th><th className="px-4 py-3 font-medium">Officer</th><th className="px-4 py-3 font-medium">Progress</th><th className="px-4 py-3 font-medium">Status</th><th/></tr></thead><tbody>{patrols.map((patrol)=><tr key={patrol.id} className="border-t border-[var(--np-line)]"><td className="px-4 py-3"><p className="font-medium">{patrol.route}</p><p className="text-xs text-[var(--np-muted)]">{patrol.area}</p></td><td className="px-4 py-3">{patrol.officer}</td><td className="px-4 py-3"><div className="flex items-center gap-2"><span className="h-1.5 w-22 overflow-hidden rounded-full bg-slate-100"><i className="block h-full rounded-full bg-[var(--np-brand)]" style={{width:`${patrol.progress}%`}}/></span><span className="text-xs text-[var(--np-muted)]">{patrol.checkpoints}</span></div></td><td className="px-4 py-3"><StatusBadge tone={patrol.status === "active" ? "live" : patrol.status === "complete" ? "success" : "warning"}>{patrol.status === "active" ? "In progress" : patrol.status}</StatusBadge></td><td className="px-4 py-3 text-right"><ArrowRightIcon size={17} className="text-[var(--np-brand)]"/></td></tr>)}</tbody></table></div></LayerCard></div>
      <div><SectionHeading title="Personnel status" action={<span className="text-xs text-[var(--np-muted)]">{personnel.length} shown</span>}/><LayerCard className="divide-y divide-[var(--np-line)] overflow-hidden shadow-sm ring-1 ring-[var(--np-line)]">{personnel.slice(0,4).map((person)=><div key={person.id} className="flex items-center gap-3 px-4 py-3"><span className="grid size-9 place-items-center rounded-full bg-slate-100 text-xs font-medium">{person.initials}</span><div className="min-w-0 flex-1"><p className="truncate font-medium">{person.name}</p><p className="truncate text-xs text-[var(--np-muted)]">{person.area}</p></div><StatusBadge tone={person.status === "Patrolling" ? "live" : person.status === "Late" ? "critical" : "success"}>{person.status}</StatusBadge></div>)}</LayerCard></div></div>
    <PatrolFormDialog open={patrolDialogOpen} onOpenChange={setPatrolDialogOpen} mode="create" onSubmit={handleCreatePatrol} />
  </div>;
}
